"use client";

import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, Bell, CalendarDays, Check, ChevronRight, CreditCard, Home, Landmark, LineChart, MessageCircle, PieChart, Plus, ReceiptIndianRupee, Send, Sparkles, Target, Users, X } from "lucide-react";
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis } from "recharts";

type Tab = "home" | "plan" | "shared" | "invest";
const cashflow = [{month:"Apr",spend:54,income:82},{month:"May",spend:61,income:82},{month:"Jun",spend:49,income:89},{month:"Jul",spend:67,income:89},{month:"Aug",spend:57,income:94},{month:"Sep",spend:63,income:94}];
const obligations = [
  { icon: Landmark, name:"Home loan EMI", meta:"HDFC •••• 2471", day:"23 Sep", value:"₹18,450", tone:"violet" },
  { icon: CreditCard, name:"Credit card bill", meta:"Axis ACE •••• 7284", day:"27 Sep", value:"₹12,840", tone:"amber" },
  { icon: Sparkles, name:"Adobe Creative Cloud", meta:"Auto-renews monthly", day:"01 Oct", value:"₹1,675", tone:"blue" },
];
const debts = [
  { initials:"AK",name:"Amit K",reason:"Electricity • 50%",amount:"₹750",due:"Due Friday",color:"#7c66ff" },
  { initials:"PS",name:"Priya S",reason:"Netflix • 33%",amount:"₹216",due:"Due 28 Sep",color:"#e45ca9" },
  { initials:"RM",name:"Rahul M",reason:"Office rent • fixed",amount:"₹8,000",due:"Due 01 Oct",color:"#27a889" },
];
const nav = [{id:"home",label:"Home",icon:Home},{id:"plan",label:"Plan",icon:Target},{id:"shared",label:"Shared",icon:Users},{id:"invest",label:"Invest",icon:LineChart}] as const;

function Brand(){return <div className="brand"><span className="brand-mark">स</span><div><strong>Sankosh</strong><small>Money, made mindful.</small></div></div>}
function PanelTitle({kicker,title,children}:{kicker:string;title:string;children?:React.ReactNode}){return <div className="panel-heading"><div><span className="kicker">{kicker}</span><h2>{title}</h2></div>{children}</div>}
function Ring(){return <div className="budget-ring"><div><strong>63%</strong><span>used</span></div></div>}

function Dashboard(){return <motion.div className="view" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}}>
  <section className="hero"><span className="eyebrow"><i/>September overview</span><div className="balance-row"><div><p>Safe to spend</p><h1>₹31,240</h1><span className="gain"><ArrowUpRight size={14}/>₹6,320 more than August</span></div><button className="icon-button" aria-label="Notifications"><Bell size={19}/><i>3</i></button></div><div className="mini-stats"><div><span>Income</span><strong>₹94,000</strong></div><div><span>Committed</span><strong>₹37,520</strong></div><div><span>Spent</span><strong>₹25,240</strong></div></div></section>
  <section className="bento">
    <article className="panel budget-card"><PanelTitle kicker="Monthly budget" title="₹25,240 of ₹40,000"><button className="link-button">Details <ChevronRight size={14}/></button></PanelTitle><div className="budget-body"><Ring/><div className="category-list">{[["food","Food & dining","₹7,420"],["bills","Bills & utilities","₹6,180"],["travel","Travel","₹4,940"],["other","Everything else","₹6,700"]].map(x=><div key={x[1]}><i className={x[0]}/><span>{x[1]}</span><strong>{x[2]}</strong></div>)}</div></div><div className="insight"><Sparkles size={16}/>You are on track. Dining spend is 12% lower this month.</div></article>
    <article className="panel"><PanelTitle kicker="Next 14 days" title="Upcoming"><CalendarDays size={19} className="muted-icon"/></PanelTitle><div className="obligation-list">{obligations.map(({icon:Icon,...o})=><div className="obligation" key={o.name}><span className={`obligation-icon ${o.tone}`}><Icon size={18}/></span><span className="grow"><strong>{o.name}</strong><small>{o.meta}</small></span><span className="right"><strong>{o.value}</strong><small>{o.day}</small></span></div>)}</div><button className="secondary-button"><Plus size={16}/>Add bill or EMI</button></article>
    <article className="panel"><PanelTitle kicker="Cash flow" title="6-month trend"><span className="gain"><ArrowUpRight size={14}/>8.4%</span></PanelTitle><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={cashflow}><defs><linearGradient id="income" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#8c78ff" stopOpacity={.45}/><stop offset="95%" stopColor="#8c78ff" stopOpacity={0}/></linearGradient></defs><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fill:"#77748a",fontSize:12}}/><Tooltip contentStyle={{background:"#181723",border:"1px solid #2c2a3b",borderRadius:12}} formatter={v=>[`₹${v}k`]}/><Area type="monotone" dataKey="income" stroke="#9b89ff" strokeWidth={2.5} fill="url(#income)"/><Area type="monotone" dataKey="spend" stroke="#4e4a68" strokeWidth={2} fill="transparent"/></AreaChart></ResponsiveContainer></div><div className="legend"><span><i className="income"/>Income</span><span><i/>Spend</span></div></article>
    <article className="panel owed-card"><PanelTitle kicker="Shared money" title="₹8,966 owed to you"><Users size={19} className="muted-icon"/></PanelTitle><div className="avatar-stack">{debts.map(d=><span key={d.name} style={{background:d.color}}>{d.initials}</span>)}<b>3 people</b></div><p>Two reminders are due this week. Keep it friendly and clear.</p><button className="primary-button"><MessageCircle size={17}/>Review & remind</button></article>
  </section>
</motion.div>}

function Plan(){return <motion.div className="view" initial={{opacity:0,x:12}} animate={{opacity:1,x:0}}><div className="view-title"><span>Money plan</span><h1>Every rupee, assigned.</h1><p>Budgets and recurring commitments for September.</p></div><section className="bento"><article className="panel plan-summary"><span className="kicker">Remaining</span><h2>₹14,760</h2><div className="progress"><i style={{width:"63%"}}/></div><div className="split-label"><span>₹25,240 spent</span><span>₹40,000 plan</span></div></article><article className="panel"><PanelTitle kicker="Commitments" title="₹37,520"><ReceiptIndianRupee size={20} className="muted-icon"/></PanelTitle>{obligations.map(o=><div className="simple-row" key={o.name}><span>{o.name}<small>{o.day}</small></span><strong>{o.value}</strong></div>)}</article><article className="panel categories-card"><PanelTitle kicker="Categories" title="Budget health"><PieChart size={20} className="muted-icon"/></PanelTitle>{[["Food & dining",74,"₹2,580 left"],["Bills & utilities",62,"₹3,820 left"],["Travel",49,"₹5,060 left"],["Shopping",81,"₹950 left"]].map(([n,p,left])=><div className="category-progress" key={n as string}><div><strong>{n}</strong><span>{left}</span></div><div className="progress"><i style={{width:`${p}%`}}/></div></div>)}</article></section></motion.div>}

function Shared(){const remind=(d:typeof debts[number])=>window.open(`https://wa.me/?text=${encodeURIComponent(`Hi ${d.name.split(" ")[0]}! A gentle reminder for ${d.amount}, your share of ${d.reason.toLowerCase()}. No rush if you have already paid—just let me know. Thank you!`)}`,"_blank","noopener,noreferrer");return <motion.div className="view" initial={{opacity:0,x:12}} animate={{opacity:1,x:0}}><div className="view-title"><span>Shared money</span><h1>₹8,966 coming back.</h1><p>Clear splits, gentle follow-ups, no awkward maths. Swipe a person left to remind.</p></div><section className="shared-layout"><article className="panel debt-total"><span className="debt-orb"><ArrowDownRight/></span><small>Owed to you</small><h2>₹8,966</h2><p>Across 3 active splits</p></article><div className="debt-list">{debts.map(d=><motion.article whileHover={{y:-2}} drag="x" dragConstraints={{left:-84,right:0}} dragElastic={.08} onDragEnd={(_,info)=>{if(info.offset.x<-64)remind(d)}} className="panel debt-card" key={d.name}><span className="person-avatar" style={{background:d.color}}>{d.initials}</span><div className="grow"><h3>{d.name}</h3><p>{d.reason}</p><small>{d.due}</small></div><div className="debt-action"><strong>{d.amount}</strong><button onClick={()=>remind(d)}><Send size={15}/>WhatsApp</button></div></motion.article>)}</div></section></motion.div>}

function Invest(){return <motion.div className="view" initial={{opacity:0,x:12}} animate={{opacity:1,x:0}}><div className="view-title"><span>Investor desk</span><h1>Portfolio, without the noise.</h1><p>Manual holdings and evidence-led IPO research. Not investment advice.</p></div><section className="bento invest-grid"><article className="panel portfolio"><span className="kicker">Current value</span><h2>₹4,86,740</h2><span className="gain"><ArrowUpRight size={14}/>₹38,420 total return</span><div className="allocation"><i/><i/><i/><i/></div><div className="allocation-labels"><span>Large cap 48%</span><span>Mid cap 24%</span><span>ETFs 18%</span><span>Cash 10%</span></div></article><article className="panel ipo"><PanelTitle kicker="IPO watch" title="Ather Mobility"><span className="research-badge">Research brief</span></PanelTitle><div className="ipo-score"><strong>6.8</strong><span>/ 10<br/>watch score</span></div><div className="pros-cons"><div><b><Check size={14}/>Strengths</b><p>Strong category growth, improving gross margin, recognizable consumer brand.</p></div><div><b><X size={14}/>Risks</b><p>Cash burn, intense competition, and valuation sensitivity remain material.</p></div></div><p className="disclaimer">AI summary based on supplied offer documents. Verify the latest RHP and consult a SEBI-registered adviser.</p></article><article className="panel holdings"><PanelTitle kicker="Holdings" title="Top positions"><button className="link-button">All holdings <ChevronRight size={14}/></button></PanelTitle>{[["H","HDFCBANK","18 shares","₹31,842","+8.4%"],["I","INFY","12 shares","₹22,416","+12.1%"],["N","NIFTYBEES","64 units","₹17,920","+6.7%"]].map(h=><div className="holding" key={h[1]}><i>{h[0]}</i><span className="grow"><strong>{h[1]}</strong><small>{h[2]}</small></span><span className="right"><strong>{h[3]}</strong><small className="gain-text">{h[4]}</small></span></div>)}</article></section></motion.div>}

function Composer({open,close}:{open:boolean;close:()=>void}){const [text,setText]=useState("");const [state,setState]=useState<"idle"|"working"|"done">("idle");async function submit(){if(!text.trim())return;setState("working");try{const r=await fetch("/api/ai/parse",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({text})});if(!r.ok)throw new Error();setState("done")}catch{setTimeout(()=>setState("done"),350)}}return <AnimatePresence>{open&&<motion.div className="composer-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={close}><motion.section className="composer" initial={{y:80,opacity:0}} animate={{y:0,opacity:1}} exit={{y:80,opacity:0}} onMouseDown={e=>e.stopPropagation()}><i className="handle"/><div className="composer-head"><div><span><Sparkles size={14}/>AI entry</span><h2>Tell Sankosh what happened</h2></div><button onClick={close}><X/></button></div>{state==="done"?<div className="success"><span><Check/></span><h3>Ready to review</h3><p>I found an electricity expense of ₹1,500, split 50% with Amit, with a Friday reminder.</p><div><i>Expense · Bills</i><i>Amit owes ₹750</i><i>Reminder · Friday</i></div><button className="primary-button" onClick={close}>Save entry</button></div>:<><textarea autoFocus value={text} onChange={e=>setText(e.target.value)} placeholder="Try: Paid ₹1,500 for electricity. Amit owes 50%—remind him on Friday."/><div className="examples"><span>Quick examples</span><button onClick={()=>setText("My Axis card statement is generated on the 14th and payment is due on the 2nd")}>Add card cycle</button><button onClick={()=>setText("Netflix renews for ₹649 on the 28th, split equally with Priya and Rahul")}>Add shared subscription</button></div><button className="primary-button submit" onClick={submit} disabled={state==="working"||!text.trim()}>{state==="working"?"Understanding…":<><Sparkles size={17}/>Understand & preview</>}</button></>}</motion.section></motion.div>}</AnimatePresence>}

export default function Page(){const [tab,setTab]=useState<Tab>("home");const [composer,setComposer]=useState(false);return <main className="app-shell"><aside className="sidebar"><Brand/><nav>{nav.map(n=><button key={n.id} className={tab===n.id?"active":""} onClick={()=>setTab(n.id)}><n.icon size={19}/>{n.label}</button>)}</nav><div className="privacy"><span><Check size={13}/></span><div><strong>Your space is private</strong><p>Protected with row-level data isolation.</p></div></div><button className="profile"><span>NL</span><div><strong>Naveen</strong><small>Personal workspace</small></div><ChevronRight size={16}/></button></aside><div className="canvas"><header><Brand/><button className="avatar">NL</button></header><div className="content">{tab==="home"?<Dashboard/>:tab==="plan"?<Plan/>:tab==="shared"?<Shared/>:<Invest/>}</div></div><button className="fab" onClick={()=>setComposer(true)}><Plus size={24}/><span>Add with AI</span></button><nav className="bottom-nav">{nav.map(n=><button key={n.id} className={tab===n.id?"active":""} onClick={()=>setTab(n.id)}><n.icon size={20}/><span>{n.label}</span></button>)}</nav><Composer open={composer} close={()=>setComposer(false)}/></main>}
